# Generated by Django 5.1.4 on 2026-01-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultomatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
