# Generated by Django 5.1.4 on 2026-01-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultomatic', '0002_alter_animation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='fps',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='animation',
            name='frame_size',
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name='animation',
            name='sheet_size',
            field=models.IntegerField(default=1024),
        ),
    ]
