# Generated by Django 5.1.4 on 2025-01-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=7)),
                ('session_id', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DancePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.PositiveSmallIntegerField(db_index=True)),
                ('start_y', models.PositiveSmallIntegerField(db_index=True)),
                ('end_x', models.PositiveSmallIntegerField(db_index=True)),
                ('end_y', models.PositiveSmallIntegerField(db_index=True)),
                ('delta_x', models.SmallIntegerField(db_index=True)),
                ('delta_y', models.SmallIntegerField(db_index=True)),
                ('event_timestamp', models.PositiveIntegerField()),
                ('click_time_delta', models.IntegerField()),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='pixeldance.dancer')),
            ],
        ),
    ]
