# Generated by Django 5.1.4 on 2025-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixeldance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
