# Generated by Django 5.1.4 on 2025-01-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixeldance', '0002_alter_dancer_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancer',
            old_name='session_id',
            new_name='session_key',
        ),
    ]
