# Generated by Django 5.1.4 on 2025-02-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixeldance', '0003_rename_session_id_dancer_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancepath',
            name='event_timestamp',
            field=models.PositiveBigIntegerField(),
        ),
    ]
