# Generated by Django 5.1.4 on 2025-01-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
