# Generated by Django 5.1.4 on 2025-01-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
