# Generated by Django 5.1.4 on 2025-01-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_sponsorprofile_company_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsormessage',
            options={'ordering': ['-created_at']},
        ),
    ]
