# Generated by Django 5.1.4 on 2025-01-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_alter_sponsormessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('reader_session_key', models.CharField(max_length=40)),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsormessage')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsor')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
    ]
