# Generated by Django 5.1.4 on 2025-01-25 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_fundscredit_fundsdebit_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cashier.stripepayment'),
        ),
    ]
