# Generated by Django 5.1.4 on 2025-01-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundscredit',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='cashier.order'),
        ),
    ]
