site_name: MYCTP Documentation
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Overview: overview.md
  - Features:
    - Projects: features/projects.md
    - Community: 
      - Overview: features/community/overview.md
      - Sponsors: features/community/sponsors.md
      - Meditations: features/community/meditations.md
      - Reflections: features/community/reflections.md
      - Pixeldance: features/community/pixeldance.md
      - Our Disco Tech?: features/community/our-disco-tech-teaser.md
    - Our Disco Tech: 
      - Overview: features/our-disco-tech/overview.md
  - Development:
    - Getting Started:
      - Installation: development/getting-started/installation.md
      - Configuration: development/getting-started/configuration.md
      - Contributing: development/getting-started/contributing.md
    - Frontend:
      - Overview: development/frontend/overview.md
      - Add Frontend: development/frontend/adding-frontends.md
      - Components: development/frontend/components.md
    - Backend:
      - Overview: development/backend/overview.md
      - API: development/backend/api.md
    - Deployment: development/deployment.md
    - Testing: development/testing.md
    - Learning: development/learning.md
    - Security Research: development/security-research.md