# Generated by Django 5.1.4 on 2025-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebirth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='original_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='public_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
