# Generated by Django 5.1.4 on 2025-02-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebirth', '0002_alter_avatar_original_hash_alter_avatar_public_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ['-created_at']},
        ),
    ]
