# Generated by Django 5.1.4 on 2025-02-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('edit_plane', models.CharField(default='x', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Voxel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=6)),
                ('x', models.IntegerField(db_index=True)),
                ('y', models.IntegerField(db_index=True)),
                ('z', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('is_placed', models.BooleanField(db_index=True, default=False)),
                ('voxel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildforge.voxel')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_holding', models.BooleanField(db_index=True, default=False)),
                ('voxel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildforge.voxel')),
            ],
        ),
    ]
