# Generated by Django 5.1.4 on 2025-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildforge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='voxel',
            name='claim_pending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='builder',
            name='edit_plane',
            field=models.CharField(default='xy', max_length=2),
        ),
        migrations.AlterField(
            model_name='builder',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='builder',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='builder',
            name='z',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placementpromise',
            name='z',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voxel',
            name='color',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
