# Generated by Django 5.1.4 on 2025-02-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildforge', '0002_alter_claim_options_voxel_claim_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voxel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
