# Generated by Django 5.1.4 on 2025-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildforge', '0003_voxel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voxel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
