# Generated by Django 5.1.4 on 2024-12-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techprojects', '0002_alter_location_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectregistration',
            old_name='sumbission_date',
            new_name='submission_date',
        ),
    ]
