# Generated by Django 5.1.4 on 2024-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techprojects', '0005_projectregistration_repo_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectregistration',
            name='repository_url',
            field=models.URLField(unique=True),
        ),
    ]
