# Generated by Django 5.1.4 on 2024-12-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techprojects', '0006_alter_projectregistration_repository_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectregistration',
            name='repository_url',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
