# Generated by Django 5.1.4 on 2025-01-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techprojects', '0007_alter_projectregistration_repository_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectregistration',
            options={'ordering': ['-last_updated']},
        ),
    ]
